### ISSUE TITLE
Selecting the language manually

### ISSUE THREAD

**Issue by yaeszlo** [cibernox/svelte-intl-precompile#11]
Hello, thanks for making this library!

Is it possible to implement this with manual language selection? 
Simple dropdown menu on the navbar with few possible languages to select, usual stuff

Thanks

**Comment by cibernox** [comment]
Sure. It would be done just the exact same way one would in `svelte-i18n`, as the API is nearly 100% compatible.

Check this implementation with buttons: https://github.com/cibernox/sveltekit-bug-with-plugin/blob/main/src/routes/index.svelte#L32-L35
Doing the dropdown is up to you, but you just have to set `$locale` to the new locale and everything will update.
