### ISSUE TITLE
pluralized not working

### ISSUE THREAD

**Issue by yadoga** [cibernox/svelte-intl-precompile#13]
following the example 
```
"foot": "{count} {count, plural, =1 {foot} other {feet}}"
```
using the standard way to call
```
$t('foot', { values: { count: 2 } })
```

…outputs the translation string logic itself:
```
=> {count} {count, plural, =1 {foot} other {feet}}
```

_running latest SvelteKit version_

**Comment by cibernox** [comment]
Can you verify your setup looks somewhat similar to the one in this demo app: https://github.com/cibernox/quick-i18n-throwaway-demo/

Particularly pay attention to https://github.com/cibernox/quick-i18n-throwaway-demo/blob/main/svelte.config.js and https://github.com/cibernox/quick-i18n-throwaway-demo/blob/main/src/routes/index.svelte

**Comment by yadoga** [comment]
Thanks, paid close attention to those. Regular translations do work fine. I guess my issue is also a duplicate of #7 ...

That being said, the problem persists for now on my end.

**Comment by yadoga** [comment]
Just cloned your barebones repo and it is working for me. Now trying to find a particular difference that's holding my setup up...

**Comment by yadoga** [comment]
Cleaned up package.json, everything working now! Was not yet able to pinpoint the root cause. I'm suspected some typescript packages but cannot confirm that just yet. Closing this, thanks again!

**Comment by cibernox** [comment]
Glad you fixed it!
