### ISSUE TITLE
 [vite] Internal server error: unknown: INVALID_ARGUMENT_TYPE

### ISSUE THREAD

**Issue by xellDart** [cibernox/svelte-intl-precompile#28]
Hi, thanks for your hard work, I have a problem with your library, I can't get this work :(

<a href="https://ibb.co/YDGh4Km"><img src="https://i.ibb.co/vs8kCrp/Captura-de-Pantalla-2021-11-18-a-la-s-21-40-03.png" alt="Captura-de-Pantalla-2021-11-18-a-la-s-21-40-03" border="0"></a>

An in chrome I get:

<a href="https://ibb.co/SsBQKZz"><img src="https://i.ibb.co/C1QJnSf/Captura-de-Pantalla-2021-11-18-a-la-s-21-42-00.png" alt="Captura-de-Pantalla-2021-11-18-a-la-s-21-42-00" border="0"></a>

I can't understand what is wrong, can you help me please?

**Comment by cibernox** [comment]
Maybe there is something wrong with some ICU string? Is this some project you can share? Since I suspect it's because of the translations, perhaps just sharing the translations JSON files could suffice
