### ISSUE TITLE
Support for 18n-ally VS Code extension

### ISSUE THREAD

**Issue by mr-islam** [cibernox/svelte-intl-precompile#29]
Hi, thank you for your work :)

Maybe this is out of scope, but when working with anything i18n, the [i18n-Ally](https://github.com/lokalise/i18n-ally) extension makes work really fast and easy. It would be awesome to get support for this, like svelte-i18n already does

**Comment by cibernox** [comment]
It would indeed. I don't know what changes are required, I should investigate that. The API is almost identical so it shouldn't be hard

**Comment by mr-islam** [comment]
Oh my, thank you for your super fast response!

I was exploring to try get it working… after about an hour, the most simple thing got it working: manually selecting Svelte as the framework in the extension settings

`"i18n-ally.enabledFrameworks": [
  "svelte"
]`

So presumably, it failed to auto-detect because either:

- didn't find svelte-i18n syntax (not likely because it's pretty much the same, changing `t` for `_`)
- doesn't support sveltekit seamlessly (in which case it's an issue for the extension / the template for this library)

If you could confirm this solution works for you, documenting it would be awesome

Thank you so much 🌹

**Comment by RickMeijer** [comment]
Just a random guy, but I can confirm adding svelte to the enabledFrameworks has my 18nally extension working as well.

**Comment by cibernox** [comment]
Thanks, I believe this can be closed now.

**Comment by cibernox** [comment]
For completeness, I've requested this library to be officially supported out of the box: https://github.com/lokalise/i18n-ally/issues/712

Hopefully it won't take too long.
