### ISSUE TITLE
Duplicate next input field

### ISSUE THREAD

**Issue by stalkerg** [cibernox/svelte-intl-precompile#3]
If I have next code:
```html
{$t('Page')}:
<input type="number"
              name="page"
              step="1"
              size="3"
              value={pageNumber}
>
```

it removes `:` and duplicates this input. Looks like the parser is broken. 
![изображение](https://user-images.githubusercontent.com/1853716/116778235-a2a84b80-aaab-11eb-985c-8b997af7f455.png)

**Comment by stalkerg** [comment]
It's was Svelte 3.38 issue.

**Comment by cibernox** [comment]
Glad to hear! 😀
