### ISSUE TITLE
add github sponsors or open collective

### ISSUE THREAD

**Issue by sastan** [cibernox/svelte-intl-precompile#31]
We would like to support this library and your (@cibernox) effort maintaining it. Could you create an open collective or github sponsors page?

**Comment by cibernox** [comment]
That's very thoughtful of you, thank you very much. 

I opened a github sponsors profile. It's in review, I don't know how quickly these things go.
In the past (before GH sponsors existed) I've taken contributions for other open source work via PayPal (https://ember-power-select.com/support-the-project) in case you don't want to wait for GH sponsors to get approved.

And thank **you** for your quick fix to precompile-intl-runtime ❤️

**Comment by sastan** [comment]
Awesome... I'll check with the _powers above_.

**Comment by cibernox** [comment]
FWIW, GH sponsors is approved now.
