### ISSUE TITLE
Failed to resolve import "$locales/en.js"

### ISSUE THREAD

**Issue by pptavozl** [cibernox/svelte-intl-precompile#35]
Hello, I'm following first steps configuration
https://svelte-intl-precompile.com/es/docs/getting-started

but I'm getting this error from __layout.svelte

```
Failed to resolve import "$locales/en.js" from "src/routes/__layout.svelte". Does the file exist?
3  |  
4  |  import { init, waitLocale } from 'svelte-intl-precompile';
5  |  register('en', () => import('$locales/en.js'));
   |                              ^
6  |  register('es', () => import('$locales/es.js'));
7  | 
```

$locales path is not working..

Any other configuration to do ?

SOLVED:
Added to config.kit.vite level instead config.vite level
![image](https://user-images.githubusercontent.com/7065779/147614599-3381ffb5-80aa-4238-98bb-5268e9462b3c.png)

**Comment by cibernox** [comment]
Glad you found it so quick!

**Comment by MordragT** [comment]
I am getting the same error, but as svelte kit does not expose vite configuration anymore, i added the plugin to vite.config.ts:

```ts
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';
import precompileIntl from "svelte-intl-precompile/sveltekit-plugin";

const config: UserConfig = {
	plugins: [
		precompileIntl("locales"),
		sveltekit()
	]
};

export default config;
```
