### ISSUE TITLE
Can't properly import for new ES6 modules config file

### ISSUE THREAD

**Issue by stalkerg** [cibernox/svelte-intl-precompile#4]
Currently, svelte.config.js is an ES6 module and svelte-intl-precompile should support it. 
In the current situation, I should write:
```js
import precompileIntl from 'svelte-intl-precompile/sveltekit-plugin.js';
```

**Comment by cibernox** [comment]
Interesting, I have `svelte.config.cjs` so just use `const precompileIntl = require("svelte-intl-precompile/sveltekit-plugin");`

I might have to generate both systems
