### ISSUE TITLE
vite-plugin-svelte warning about svelte-intl-precompile during SvelteKit build

### ISSUE THREAD

**Issue by abastardi** [cibernox/svelte-intl-precompile#40]
When building a SvelteKit app via `npm run build`, I'm getting the following warning about `svelte-intl-precompile` in the output (note, this does not seem to be causing any problems with the package functioning properly):

```
[vite-plugin-svelte] vite-plugin-svelte was unable to find package.json of the following packages and wasn't able to resolve via their "svelte" field.
If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- svelte-intl-precompile
```

**Comment by cibernox** [comment]
That's somewhat expected. My understanding is that the "svelte" field on the package.json must be used indicate the entry point for svelte components, but this package doesn't expose any component, only JS utilities.
I wonder if there's a way of silencing this warning when it doesn't apply.

**Comment by abastardi** [comment]
That makes sense. Thanks for the response, and for your work on this package.

**Comment by cibernox** [comment]
I've been told that the newest version of `vite-plugin-svelte` should have that warning fixed. I believe that if you update it will be gone. 

I'll close it for now.
