### ISSUE TITLE
Feature request: Config option to ignore specific file names/types

### ISSUE THREAD

**Issue by venashial** [cibernox/svelte-intl-precompile#48]
We use a git submodule for [our translations](https://github.com/modrinth/translations), so a `crowdin.yml` file ends up in the `locales` folder. It would be nice if we could ignore it.

**Comment by cibernox** [comment]
good point. IMO in fact only locales named after ISO language codes should be considered. E.g. `en.yml` or `en-US.yml`, but any file not matching `/\w\w(-\w\w)?\.\w*/` should be ignored.

**Comment by cibernox** [comment]
I released 0.10.1 with a change. Only files with a name that maches the ISO code of a language (with or without regional variant) are considered locales. Give it a try.

**Comment by venashial** [comment]
Thanks! That works.
