### ISSUE TITLE
JSON support?

### ISSUE THREAD

**Issue by cupcakearmy** [cibernox/svelte-intl-precompile#5]
Hey, saw your talk at Svelte Summit and i love it. Makes so much sense!
A question about usage: i tried using json instead of js files but it don't work, probably because bable only applies to js. Now my question is: is there a way to make it work with json files? most platforms like lokalise do not support js files, also most of the i18n extensions also require json files. Unfortunately, using js files makes it quite impossible in bigger projects. Do you know any way around this?

Thanks!

**Comment by cibernox** [comment]
I'd love to support JSON files. It was my initial idea but I couldn't find a way with svelte/vite of making the plugin run after `vite:json` but before svelte-kit preprocesses all import statements.  
It's almost surely something workable, but I don't know enough about the build pipeline.

**Comment by cupcakearmy** [comment]
Thanks! Yeah i have 0 expertise in bundler pipelines. Feel free to close it, i'll probably look to generate the files then :)

**Comment by cibernox** [comment]
As soon as I have time I'm going to give it another go. I'm sure there must be a way.

**Comment by cupcakearmy** [comment]
That would be awesome of course :)

**Comment by Valexr** [comment]
I'm use json for dictionaries now on esbuild bundler 🤷🏻‍♂️

```js
import en from "@lang/en.json";

addMessages("en", en);
```

**Comment by cibernox** [comment]
@Valexr could you explain more? I didn't even know that svelte could do that.

**Comment by Valexr** [comment]
Sure @cibernox 🤓
It’s not svelte, it’s esbuild can imports .json files to bundle by default🤷🏻‍♂️ But I’m not sure about i18n logic operators… don’t use it.

Simple starter for testing https://github.com/AlexxNB/svelte-esbuild-starter just try it. & update esbuild to 0.11.* minor please.

**Comment by lorenzosignoretti** [comment]
+1 I'd love to see the support for `.json` files. It would make it easier to use the library in conjunction with tools such as [Lokalise](https://www.lokalise.com).

**Comment by cibernox** [comment]
Indeed, it's probably the thing I miss the most myself when using it. My sveltekit (or Vite really) skills might not be sharp enough to do that without help, as it's a bit tricky. You want to import a js file that doesn't exist and have it resolved to a generated-on-the-fly JS file from a JSON source.

I'll check if someone with more experience can help with that.

**Comment by uSide** [comment]
@cibernox tried to implement this in #16

**Comment by cibernox** [comment]
Released this feature in 0.4.0. The version bump wasn't really necessary as this is backwards compatible but it's there just to signal a significant feature.

**Comment by cibernox** [comment]
I now recommend people define it's translations in json files, there is no reason to use javascript/typescript anymore.
