### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by gerukin** [cibernox/svelte-intl-precompile#53]
Awesome library, thank you for the hard work! 🙇 As a matter of fact, I switched to it because of some issues in the pre-rendering pipeline with `svelte-i18n` (in addition to the other benefits) and it was an exceptionally smooth transition.... with one exception. 😁

Consider the following, which works:
```json
{
    "duration": "{years, plural, =0 { } one {#年} other {#年}} {months, plural, =0 { } one {#ヶ月} other {#ヶ月}}"
}
```

And the following, which doesn't:
```json
{
    "duration": "{years, plural, =0 { } one {#年} other {#年}}{months, plural, =0 { } one {#ヶ月} other {#ヶ月}}"
}
```
> Number of TemplateLiteral quasis should be exactly one more than the number of expressions.
Expected 3 quasis but got 1

The only difference is the space between the 2 main blocks.

Now I can add the space back in the middle, and instead remove the space in the first `{}`:
```json
{
    "duration": "{years, plural, =0 {} one {#年} other {#年}} {months, plural, =0 { } one {#ヶ月} other {#ヶ月}}"
}
```

No error but the output (with `0` and `11` for the values) is:
> () => `` 11ヶ月

No issue with values other than `0`. Also, FYI it worked fine in `svelte-i18n`.

Thanks again!

**Comment by cibernox** [comment]
Thanks! I think the compiler didn't account for the posibility of a "translation path" being empty. I didn't cross my mind that it was a possibility. I'll improve the build time compiler to account for that.

**Comment by cibernox** [comment]
I think I've fixed it. Run `npm update babel-plugin-precompile-intl` and it should work.
