### ISSUE TITLE
Not showing warning for empty string translation

### ISSUE THREAD

**Issue by EskelCz** [cibernox/svelte-intl-precompile#56]
Thanks for this awesome library. :) Just a super simple question/request.
Does it make sense to throw a warning for `$t('')` that `''` was not found in the dictionary?
Because I don't think think translating an empty string to something else is very useful. :)

I like both my code and console as clean as possible and this forces me to add a lot of ugly checks for empty strings.
Thanks for your consideration.

**Comment by cibernox** [comment]
I think it makes sense to show a warning for any attempt to translate a key that is not in the dictionary of known keys. At most I'd concede that for this case it could be a different warning. I'd expect that if someone tries to translate an empty string that's probably an unintender bug/typo.
