### ISSUE TITLE
Documentation not reachable

### ISSUE THREAD

**Issue by timonmasberg** [cibernox/svelte-intl-precompile#58]
https://svelte-intl-precompile.com/ seems to be not working anymore :( 404

**Comment by AM-77** [comment]
you can access it via https://svelte-intl-precompile.com/en/docs/configuration, but https://svelte-intl-precompile.com/  still broken!

**Comment by cibernox** [comment]
It's reachable again!! Something happened in the last month in sveltekit that the issue is now fixed
