### ISSUE TITLE
Variables in string inside arrays do not work

### ISSUE THREAD

**Issue by vegardlarsen** [cibernox/svelte-intl-precompile#62]
I tried in the playground to test something that was breaking in my project:

```json
{
  "y": "foo {bar}",
  "x": ["{foo} something"],
  "z": { "nested": "foo {bar}" }
}
```

## Output

```
import { __interpolate } from "svelte-intl-precompile";
export default {
  "y": bar => `foo ${__interpolate(bar)}`,
  "x": ["{foo} something"],
  "z.nested": bar => `foo ${__interpolate(bar)}`
};
```

Notice that the variable inside the `x` array is not interpolated.

## Expected output

This is what I expected, but it may very well need to be different.

```
import { __interpolate } from "svelte-intl-precompile";
export default {
  "y": bar => `foo ${__interpolate(bar)}`,
  "x": [foo => `${__interpolate(foo)} something`],
  "z.nested": bar => `foo ${__interpolate(bar)}`
};
```

**Comment by cibernox** [comment]
I don't think I've ever considered a translation being an array? What's the usecase for that? I never encountered it.

**Comment by vegardlarsen** [comment]
Good question. We have lists of various "product features" that sometimes contains different items in different languages. In `svelte-i18n` this was perfectly valid, but it may not be here.

I can probably work around this one if this is by design; and I can see that it may be problematic in terms of how the translations would interact e.g. with `$json`. Feel free to close this one.

**Comment by cibernox** [comment]
Out of curiosity, what does svelte-i18n do when you call `$t('x')`? Just uses the first key in the array? What if there are several entries in this array?

**Comment by vegardlarsen** [comment]
I don't know that it deals with it using `$t`. We used `$json` to extract the array, and then `getMessageFormatter` to do ICU formatting afterwards. Again, this doesn't make as much sense when precompiling.

My solution now will instead be to not use an array in the translations, and instead newline-separate the individual lines, and we can split them when using it.

**Comment by cibernox** [comment]
👍
