### ISSUE TITLE
Svelte 4 support

### ISSUE THREAD

**Issue by fatih-catalkaya** [cibernox/svelte-intl-precompile#64]
Hi,

I just wanted to ask, whether you plan on supporting Svelte 4? As it appears to me the only thing that requires to be changed is the [cibernox/precompile-intl-runtime](https://github.com/cibernox/precompile-intl-runtime) dependency to be updated to Svelte 4.

I am currently trying to investigate, however, I am not a JS developer :sweat_smile:

Regards,
Fatih

**Comment by cibernox** [comment]
Totally. I’m on holidays, I should de back this weekend and I’ll take care of this.

**Comment by macmillen** [comment]
I also need this very much

**Comment by cibernox** [comment]
@macmillen @fatih-catalkaya I published a new version that should support both svelte 3 and 4.

**Comment by macmillen** [comment]
@cibernox thank you but now I think the `svelte-intl-precompile` package also needs to upgrade the `precompile-intl-runtime` dependency to `0.8.4` and publish it's own version

**Comment by fatih-catalkaya** [comment]
Hey @cibernox just wanted to thank you for your quick response!
