### ISSUE TITLE
some @formatjs warnings appeared

### ISSUE THREAD

**Issue by yadoga** [cibernox/svelte-intl-precompile#9]
Just leaving these messages here that popped up after `npm update`:

> npm WARN deprecated intl-messageformat-parser@3.6.4: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser

> npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat

**Comment by Valexr** [comment]
+ same warning

**Comment by cibernox** [comment]
Updated, this can be closed

**Comment by usamamashkoor** [comment]
I am facing the same problem, can anyone let me know, How I can solve this issue?
